# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'm', b'Male'), (b'f', b'Female')], db_index=True, max_length=6, null=True),
        ),
    ]
