# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-26 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20200513_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_ambassador',
            field=models.BooleanField(default=False, verbose_name='Ambassador'),
        ),
    ]
