# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-11-08 11:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_userprofile_is_ambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[(b's', b'Single'), (b'm', b'Married'), (b'd', b'Divorced'), (b'w', b'Widowed')], db_index=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message=b'Mobile number must be entered in the format: "9999999999". Up to 10 digits allowed.', regex=b'^\\+?1?\\d{10}$')], verbose_name='Mobile No.'),
        ),
    ]
