# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-11-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20201108_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='center',
            field=models.CharField(blank=True, choices=[(b'ot', b'Other'), (b'ri', b'Riyadh'), (b'je', b'Jeddah'), (b'me', b'Medina'), (b'ta', b'Taif'), (b'na', b'Najran'), (b'aj', b'Al Jawf'), (b'ha', b'Haql'), (b'ab', b'Al Bahah'), (b'ra', b'Rijal Alma'), (b'da', b'Dawadmi'), (b'ya', b'Yanbu'), (b'un', b'Unaizah'), (b'am', b'Al Majmaah'), (b'aq', b'Al Qunfudhah'), (b'al', b'Al Lith'), (b'sa', b'Sabya'), (b'ak', b'Al Kharj'), (b'alu', b'AlUla'), (b'hbt', b'Hotat Bani Tamim'), (b'sh', b'shuqura'), (b'alq', b'Al-Quwayiyah'), (b'mec', b'Mecca'), (b'qa', b'Qassim'), (b'aa', b'Al Ahsa'), (b'als', b'alsharqia'), (b'ta', b'Tabuk'), (b'alm', b'almakhawa'), (b'ji', b'Jizan'), (b'ala', b'alhudud alshamalia'), (b'ar', b'Al ras'), (b'su', b'Sarat Ubaida'), (b'md', b'Mahd Dhahab'), (b'an', b'Al Nama'), (b'wd', b'Wadi Dawasir'), (b'bi', b'Bisha'), (b'abu', b'Al Bukayriyah'), (b'aaf', b'Al aflaj'), (b'qu', b'Qurayyat'), (b'mae', b'Mahayil easir'), (b'az', b'Al Zulfi'), (b'afif', b'Afif'), (b'asir', b'Asir'), (b'ag', b'Al Ghat'), (b'almu', b'Almudhanib'), (b'hfa', b'Hfr albatn'), (b'za', b'Zahran aljanub'), (b'shu', b'Sharurah')], db_index=True, max_length=64, null=True),
        ),
    ]
