# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-11-28 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_userprofile_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='mode',
            field=models.CharField(default=b'honor', max_length=100),
        ),
    ]
