# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-06 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20201128_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ambassador_edu_level',
            field=models.CharField(blank=True, choices=[(b'primary', b'Primary school'), (b'intermediate', b'Intermediate school'), (b'secondary', b'Secondary school'), (b'many_level', b'Many')], db_index=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
