# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-07 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20210206_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ambassador_edu_level',
            field=models.CharField(blank=True, choices=[(b'primary', b'Primary school'), (b'intermediate', b'Intermediate school'), (b'secondary', b'Secondary school'), (b'many_level', b'Many')], db_index=True, max_length=64, null=True, verbose_name='Ambassador Education Level'),
        ),
    ]
