# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-03-09 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20210207_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Mobile No.'),
        ),
    ]
