# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-12-12 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extra_info', '0003_educationoffice_schools'),
        ('student', '0025_auto_20210316_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extra_info.EducationOffice'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extra_info.Schools'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sector',
            field=models.CharField(blank=True, choices=[(b'ot', b'Other'), (b'ri', b'Riyadh')], db_index=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stage',
            field=models.CharField(blank=True, choices=[(b'ot', b'Other'), (b'ri', b'Riyadh')], db_index=True, max_length=512, null=True),
        ),
    ]
