# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-12-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20211212_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sector',
            field=models.CharField(blank=True, choices=[(b'private', b'Private'), (b'public', b'Public'), (b'private 2', b'Private 2')], db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stage',
            field=models.CharField(blank=True, choices=[(b'elementary', b'Elementary Level'), (b'secondary', b'Secondary Level'), (b'intermediate', b'Intermediate Level'), (b'continuous learning', b'Continuous Learning')], db_index=True, max_length=512, null=True),
        ),
    ]
