# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-01-14 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20211212_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stage',
            field=models.CharField(blank=True, choices=[(b'elementary', b'Elementary Level'), (b'secondary', b'Secondary Level'), (b'intermediate', b'Intermediate Level')], db_index=True, max_length=512, null=True),
        ),
    ]
