# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-05-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20220322_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sector',
            field=models.CharField(blank=True, choices=[(b'other', b'Other'), (b'private', b'Private'), (b'public', b'Public'), (b'private 2', b'Private 2')], db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stage',
            field=models.CharField(blank=True, choices=[(b'other', b'Other'), (b'elementary', b'Elementary Level'), (b'secondary', b'Secondary Level'), (b'intermediate', b'Intermediate Level')], db_index=True, max_length=512, null=True),
        ),
    ]
