# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-09-09 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_auto_20220523_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(blank=True, choices=[(b'ambassador', b'Ambassador Account'), (b'supervisor', b'Supervisor Account'), (b'student', b'Student Account'), (b'entrepreneur', b'Entrepreneur Account'), (b'normal', b'Normal Account')], db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_foundation',
            field=models.CharField(blank=True, choices=[(b'yes', b'Yes'), (b'no', b'No')], max_length=32, null=True, verbose_name='Do you have a company foundation?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution_age',
            field=models.CharField(blank=True, choices=[(b'0-3 years', b'0-3 years'), (b'3-6 years', b'3-6 years'), (b'more than 6 years', b'more than 6 years')], max_length=32, null=True, verbose_name='How old is the institution?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ministry_member',
            field=models.CharField(blank=True, choices=[(b'yes', b'Yes'), (b'no', b'No')], max_length=32, null=True, verbose_name='Are you a member of the Ministry of education?'),
        ),
    ]
