# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-09-15 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20220909_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(blank=True, choices=[(b'ambassador', b'Ambassador'), (b'student', b'Student'), (b'entrepreneur', b'Entrepreneur'), (b'normal', b'Normal')], db_index=True, max_length=32, null=True),
        ),
    ]
