# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2022-10-21 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_auto_20220915_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_mis_user',
            field=models.BooleanField(default=False, verbose_name='MIS User'),
        ),
    ]
