# Generated by Django 2.2.25 on 2023-01-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_registration_activation_timestamp'),
        ('student', '0033_userprofile_is_mis_user'),
    ]

    operations = [
    ]
