# Generated by Django 2.2.25 on 2023-02-04 14:27

import common.djangoapps.course_modes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_merge_20230128_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='mode',
            field=models.CharField(default=common.djangoapps.course_modes.models.CourseMode.get_default_mode_slug, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('ambassador', 'Ambassador'), ('student', 'Student'), ('entrepreneur', 'Entrepreneur'), ('normal', 'Normal')], db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ambassador_edu_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary school'), ('intermediate', 'Intermediate school'), ('secondary', 'Secondary school'), ('many_level', 'Many')], db_index=True, max_length=64, null=True, verbose_name='Ambassador Education Level'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='center',
            field=models.CharField(blank=True, choices=[('ot', 'Other'), ('ri', 'Riyadh'), ('je', 'Jeddah'), ('me', 'Medina'), ('ta', 'Taif'), ('na', 'Najran'), ('aj', 'Al Jawf'), ('ha', 'Hail'), ('ab', 'Al Bahah'), ('ra', 'Rijal Alma'), ('da', 'Dawadmi'), ('ya', 'Yanbu'), ('un', 'Unaizah'), ('am', 'Al Majmaah'), ('aq', 'Al Qunfudhah'), ('al', 'Al Lith'), ('sa', 'Sabya'), ('ak', 'Al Kharj'), ('alu', 'AlUla'), ('hbt', 'Hotat Bani Tamim'), ('sh', 'shuqura'), ('alq', 'Al-Quwayiyah'), ('mec', 'Mecca'), ('qa', 'Qassim'), ('aa', 'Al Ahsa'), ('als', 'alsharqia'), ('tab', 'Tabuk'), ('alm', 'almakhawa'), ('ji', 'Jizan'), ('ala', 'alhudud alshamalia'), ('ar', 'Al ras'), ('su', 'Sarat Ubaida'), ('md', 'Mahd Dhahab'), ('an', 'Al Nama'), ('wd', 'Wadi Dawasir'), ('bi', 'Bisha'), ('abu', 'Al Bukayriyah'), ('aaf', 'Al aflaj'), ('qu', 'Qurayyat'), ('mae', 'Mahayil easir'), ('az', 'Al Zulfi'), ('afif', 'Afif'), ('asir', 'Asir'), ('ag', 'Al Ghat'), ('almu', 'Almudhanib'), ('hfa', 'Hfr albatn'), ('za', 'Zahran aljanub'), ('shu', 'Sharurah')], db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_foundation',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=32, null=True, verbose_name='Do you have a company foundation?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institution_age',
            field=models.CharField(blank=True, choices=[('0-3 years', '0-3 years'), ('3-6 years', '3-6 years'), ('more than 6 years', 'more than 6 years')], max_length=32, null=True, verbose_name='How old is the institution?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('s', 'Single'), ('m', 'Married'), ('d', 'Divorced'), ('w', 'Widowed')], db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ministry_member',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=32, null=True, verbose_name='Are you a member of the Ministry of education?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sector',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('private', 'Private'), ('public', 'Public'), ('private 2', 'Private 2')], db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stage',
            field=models.CharField(blank=True, choices=[('other', 'Other'), ('elementary', 'Elementary Level'), ('secondary', 'Secondary Level'), ('intermediate', 'Intermediate Level')], db_index=True, max_length=512, null=True),
        ),
    ]
