# Generated by Django 5.2.11 on 2026-07-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_auto_20230204_1427'),
        ('student', '0048_mariadb_uuid_conversion'),
    ]

    operations = [
    ]
